$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sentiment-env
description: Env with pip dependencies
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: conda_env.yml
