services:
  backend:
    build: ./backend
    container_name: sentiment_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    restart: always

  frontend:
    build: ./frontend
    container_name: sentiment_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: streamlit run front.py --server.port=8501 --server.address=0.0.0.0
    restart: always
