channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - accelerate==1.8.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - numpy==1.26.4
  - pandas==2.3.1
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - torch==2.7.1
  - torchvision==0.22.1
  - transformers==4.53.2
name: mlflow-env
